### ISSUE TITLE
install failed: AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by acarl005** [tammoippen/plotille#25]
```
$ python --version
Python 3.7.3
$ pip --version
pip 19.1.1 from /Users/acarlson/anaconda3/envs/colab/lib/python3.7/site-packages/pip (python 3.7)
```

```
$ pip install plotille

Collecting plotille
  Downloading https://files.pythonhosted.org/packages/22/16/219daf27f7af6bec6b8f6dd1fe928e2723e4f9def04139aa5be8adea1800/plotille-3.7.tar.gz
  Installing build dependencies ... error
  ERROR: Complete output from command /Users/acarlson/anaconda3/envs/colab/bin/python /Users/acarlson/anaconda3/envs/colab/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/36/xqbmrgy53cb46vvzvrln93tccvpxfl/T/pip-build-env-swclygl1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel:
  ERROR: Traceback (most recent call last):
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/site-packages/pip/_internal/__init__.py", line 4, in <module>
      import locale
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Users/acarlson/anaconda3/envs/colab/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command "/Users/acarlson/anaconda3/envs/colab/bin/python /Users/acarlson/anaconda3/envs/colab/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/36/xqbmrgy53cb46vvzvrln93tccvpxfl/T/pip-build-env-swclygl1/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel" failed with error code 1 in None
```

I'm on MacOS Mojave v 10.14.6

**Comment by acarl005** [comment]
Figured it out. It was not an issue with `plotille`. Rather, I had a dependency on my system called `enum34` which was clashing with the std lib `enum` (new in 3.6). Fixed by uninstalling `enum34`. Found the answer in [this SO post](https://stackoverflow.com/a/45716067/6078821).
