### ISSUE TITLE
Histogram breaks when all values are the same

### ISSUE THREAD

**Issue by voidcase** [tammoippen/plotille#33]
```
>>> import plotille
>>> print(plotille.histogram([0,0,0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/isak/.local/share/virtualenvs/mxaimbot_trainer-A7Up_mVO/lib/python3.7/site-packages/plotille/_graphs.py", line 126, in histogram
    fig.histogram(X, bins, lc)
  File "/home/isak/.local/share/virtualenvs/mxaimbot_trainer-A7Up_mVO/lib/python3.7/site-packages/plotille/_figure.py", line 257, in histogram
    self._plots += [Histogram.create(X, bins, lc)]
  File "/home/isak/.local/share/virtualenvs/mxaimbot_trainer-A7Up_mVO/lib/python3.7/site-packages/plotille/_figure.py", line 347, in create
    frequencies, buckets = hist(X, bins)
  File "/home/isak/.local/share/virtualenvs/mxaimbot_trainer-A7Up_mVO/lib/python3.7/site-packages/plotille/_util.py", line 82, in hist
    x_idx = min(bins - 1, int(delta // xwidth))
ZeroDivisionError: float divmod()

```

using plotille version 3.7

**Comment by tammoippen** [comment]
@voidcase Thanks for the catch. Is fixed in v3.7.1.
